# Generated by Django 5.0.1 on 2024-12-10 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_foodsproduct_model_name_alter_foodsproduct_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodsproduct',
            name='category',
        ),
    ]
