# Generated by Django 5.0.1 on 2025-07-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shein', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheinproduct',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='sheinproduct',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
