# Generated by Django 5.0.1 on 2024-08-17 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_carsproduct_delivery_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonesreview',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='phones.phonesproduct'),
        ),
    ]
