# Generated by Django 5.1.4 on 2026-06-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0015_phonesproduct_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonesproduct',
            name='orders_count',
            field=models.IntegerField(default=0),
        ),
    ]
