# Generated by Django 5.0.1 on 2024-10-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerspaner', '0003_image_delete_imageupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
