# Generated by Django 5.1.4 on 2026-06-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerspaner', '0004_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='category_name',
            field=models.CharField(blank=True, help_text='اسم موديل أو قسم المنتج', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='product_id',
            field=models.IntegerField(blank=True, help_text='ID المنتج المرتبط بالبانر', null=True),
        ),
    ]
