# Generated by Django 5.1.4 on 2026-06-10 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offerspaner', '0005_image_category_name_image_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='image',
            name='product_id',
        ),
    ]
