# Generated by Django 5.1.4 on 2026-06-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerspaner', '0007_image_category_name_image_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopBannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان الإعلان')),
                ('image', models.ImageField(upload_to='top_banners/', verbose_name='صورة البانر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'صورة البانر العلوي',
                'verbose_name_plural': 'إعلانات البانر العلوي',
            },
        ),
    ]
