# Generated by Django 5.0.1 on 2024-07-17 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothesproduct',
            name='delivery_days',
            field=models.IntegerField(default=3),
        ),
    ]
