# Generated by Django 5.0.1 on 2024-12-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0007_alter_birthdayproduct_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthdayproduct',
            name='delivery_days',
            field=models.IntegerField(default=1),
        ),
    ]
