# Generated by Django 5.0.1 on 2025-06-30 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0009_birthdayproduct_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdayproduct',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
