# Generated by Django 5.0.1 on 2024-12-09 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allproducts', '0002_alter_allproduct_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allreview',
            name='product',
        ),
        migrations.RemoveField(
            model_name='allreview',
            name='user',
        ),
        migrations.DeleteModel(
            name='Allproduct',
        ),
        migrations.DeleteModel(
            name='Allreview',
        ),
    ]
