# Generated by Django 5.1.4 on 2026-06-22 11:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('allproducts', '0003_remove_allreview_product_remove_allreview_user_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('color_name', models.CharField(max_length=50, verbose_name='اسم اللون (مثال: ذهبي، فضي، أحمر)')),
                ('color_code', models.CharField(blank=True, max_length=7, null=True, verbose_name='كود اللون الهيكس (اختياري مثل: #FFFFFF)')),
                ('size', models.CharField(blank=True, max_length=30, null=True, verbose_name='المقاس (اختياري)')),
                ('variant_image1', models.ImageField(blank=True, null=True, upload_to='products/variants/')),
                ('variant_image2', models.ImageField(blank=True, null=True, upload_to='products/variants/')),
                ('variant_image3', models.ImageField(blank=True, null=True, upload_to='products/variants/')),
                ('original_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('stock', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('createAT', models.DateTimeField(default=django.utils.timezone.now)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
