# Generated by Django 5.0.1 on 2025-07-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socks', '0010_socksproduct_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socksproduct',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
