# Generated by Django 5.0.1 on 2024-12-10 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veils', '0004_veilsproduct_model_name_alter_veilsproduct_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veilsproduct',
            name='category',
        ),
    ]
