# Generated by Django 5.0.1 on 2024-12-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitsandvegetables', '0008_alter_favproduct_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favproduct',
            name='delivery_days',
            field=models.IntegerField(default=1),
        ),
    ]
