# Generated by Django 5.0.1 on 2025-06-30 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitsandvegetables', '0010_favproduct_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='favproduct',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
