# Generated by Django 5.0.1 on 2024-12-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0002_toysproduct_delivery_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toysproduct',
            name='delivery_days',
            field=models.IntegerField(default=1),
        ),
    ]
