"""
Django settings for aswaqmozhelabackend project.

Generated by 'django-admin startproject' using Django 5.0.4.
"""

from datetime import timedelta
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
SECRET_KEY = 'django-insecure-+_uhbip6ikra2&!&mnoq(1w6g1p4%ja)ds+mw@%3jgf-_nn5p0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*', '54.237.36.97', 'localhost', '127.0.0.1', '10.0.2.2']

# Application definition
INSTALLED_APPS = [
    'corsheaders',
    'itemsmainpage.apps.ItemsmainpageConfig',
    'offerspaner.apps.OfferspanerConfig',
    'allproducts.apps.AllproductsConfig',
    'supermarket.apps.SupermarketConfig',
    'accessories.apps.AccessoriesConfig',
    'gifts.apps.GiftsConfig',
    'birthday.apps.BirthdayConfig',
    'socks.apps.SocksConfig',
    'veils.apps.VeilsConfig',
    'spices.apps.SpicesConfig',
    'pharmacy.apps.PharmacyConfig',
    'fruitsandvegetables.apps.FruitsandvegetablesConfig',
    'foods.apps.FoodsConfig',
    'shein.apps.SheinConfig',
    'phones.apps.PhonesConfig',
    'toys.apps.ToysConfig',
    'order.apps.OrderConfig',
    'account.apps.AccountConfig',
    'products.apps.ProductsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'django_filters',
    'storages',  # مكتبة الربط مع AWS S3
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'mahranmostafa900@gmail.com'
EMAIL_HOST_PASSWORD = 'qjxs kjhm tfme wdrn'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False

ROOT_URLCONF = 'aswaqmozhelabackend.urls'
CORS_ALLOW_ALL_ORIGINS = True

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'aswaqmozhelabackend.wsgi.application'

# إعدادات قاعدة البيانات البطلة (PostgreSQL)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'aswaq_db',
        'USER': 'aswaq_user',
        'PASSWORD': 'Sasamanar01009345616',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# ==============================================================================
# إعدادات الـ AWS S3 والـ Media الحديثة والمتوافقة بالكامل
# ==============================================================================
AWS_ACCESS_KEY_ID = 'AKIAYYWHOIXFR4AYYLPJ'
AWS_SECRET_ACCESS_KEY = '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'
AWS_STORAGE_BUCKET_NAME = 'aswaq-mozhela-media-storage'
AWS_S3_REGION_NAME = 'us-east-1'

# إعدادات الصلاحيات وفك تشفير الروابط المؤقتة
AWS_QUERYSTRING_AUTH = False
AWS_DEFAULT_ACL = 'public-read'

# تهيئة الـ Storages للميديا فقط مع الإبقاء على الملفات الثابتة محلياً بالسيرفر
STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# نطاق ومسارات قراءة الصور مباشرة من السحاب
AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/'
# ==============================================================================

# Rest framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# JWT settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Africa/Cairo'
USE_I18N = True
USE_TZ = True

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
DEFAULT_CHARSET = 'utf-8'