# Generated by Django 5.0.1 on 2024-12-10 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spices', '0005_spicesproduct_model_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spicesproduct',
            name='category',
        ),
    ]
