# Generated by Django 5.0.1 on 2024-07-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='primary_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
