# Generated by Django 5.0.1 on 2024-10-18 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_promocode_order_delivery_fee_order_discount_amount_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromoCode',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_fee',
        ),
        migrations.RemoveField(
            model_name='order',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='subtotal_amount',
        ),
    ]
