# Generated by Django 5.0.1 on 2024-10-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_delete_promocode_remove_order_delivery_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
