# Generated by Django 5.0.1 on 2024-10-18 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_delivery_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_fee',
        ),
    ]
