# Generated by Django 5.0.1 on 2024-12-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_product_libraryproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryproduct',
            name='delivery_days',
            field=models.IntegerField(default=1),
        ),
    ]
